name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t souvik741156/go-crud .
      - name: Push image to docker hub
        run: docker push souvik741156/go-crud:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull souvik741156/go-crud:latest
      - name: Delete the old container if exist
        run: docker rm -f go-crud-container   
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name go-crud-container souvik741156/go-crud